### ISSUE TITLE
Readme for PIC32MZ-DA Starter Kit lists wrong switch

### ISSUE THREAD

**Issue by chris-mck** [Microchip-MPLAB-Harmony/bootloader_apps_uart#2]
The switch to hold during reset to force the bootloader is SW2, not SW1.
Note that SW1 is indeed the switch to launch the bootloader from the application.

**Comment by amitraddi** [comment]
Hi @chris-mck,
Thanks for reporting.
May i know if you are using a older PIC32MZ DA Adapter board? if yes then this explains the issue. on older boards Pins for the switches are interchanged.
I have a board mentioned in https://www.microchip.com/DevelopmentTools/ProductDetails/DM320010-C and it works as per documentation.

**Comment by chris-mck** [comment]
I have a DM320010 (no crypto, I re-targeted the example) with a DAR chip. The code is definitely reading from two different switches.

Bootloader. In https://github.com/Microchip-MPLAB-Harmony/bootloader_apps_uart/blob/master/apps/uart_bootloader/bootloader/firmware/src/config/pic32mz_das_sk/peripheral/gpio/plib_gpio.h:
line 71 is reading RB12.

Test App. In https://github.com/Microchip-MPLAB-Harmony/bootloader_apps_uart/blob/master/apps/uart_bootloader/test_app/firmware/src/config/pic32mz_das_sk/bsp/bsp.h:
It defines SW1=RB13, SW2=RB12, SW3=RB14.

and in https://github.com/Microchip-MPLAB-Harmony/bootloader_apps_uart/blob/master/apps/uart_bootloader/test_app/firmware/src/config/pic32mz_das_sk/user.h:
line 67 it is reading SW1 (RB13).

Edit: Holding SW1 through a reboot only appears to have the correct behaviour because it actually launches the test app which kicks back to the bootloader since the switch (SW1) is pressed. This is confirmed by watching the UART messages. I would expect the desired behaviour is to not launch the test app and remain in the bootloader, which is what happens when holding SW2 through reboot.

**Comment by amitraddi** [comment]
Hi @chris-mck ,
Wow great catch. I missed to look at the terminal log and assumed its SW1 like other devices which have only one switch. I do recall now that it was on purpose kept to  SW2 so that we do not share the switch with test_app.

We will update the documentation typo in next release. Thanks
